name: 'Activate SUSE Modules'
description: 'Activate SUSE modules (basesystem, PackageHub, legacy) on machines via SSH'

inputs:
  hosts_fqdn_list:
    description: 'Space-separated list of machine FQDNs to activate modules on'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key content'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Convert hosts list to comma-separated format
      id: prepare-hosts
      shell: bash
      run: |
        HOSTS_FQDN_LIST="${{ inputs.hosts_fqdn_list }}"
        # Convert space-separated list to comma-separated
        HOSTS_CSV=$(echo $HOSTS_FQDN_LIST | tr ' ' ',')
        echo "hosts_csv=$HOSTS_CSV" >> $GITHUB_OUTPUT
        echo "Hosts to activate: $HOSTS_CSV"

    - name: Activate SUSE modules on machines
      uses: appleboy/ssh-action@v1.2.4
      with:
        host: ${{ steps.prepare-hosts.outputs.hosts_csv }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_private_key }}
        script: |
          set -e

          source /etc/os-release

          # Skip SLES 16 machines
          if [[ "$VERSION_ID" == 16* ]]; then
            exit 0
          fi

          sudo SUSEConnect -p sle-module-basesystem/$VERSION_ID/x86_64
          sudo SUSEConnect -p PackageHub/$VERSION_ID/x86_64

          if [[ "$VERSION_ID" == "15.6" ]]; then
            sudo SUSEConnect -p sle-module-legacy/$VERSION_ID/x86_64
          fi