name: 'Terraform Destroy'
description: 'Destroy Terraform-managed infrastructure in Azure'

inputs:
  working_directory:
    description: 'Working directory for Terraform'
    required: false
    default: './terraform'

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Extract Azure Credentials
      id: azure-creds
      uses: ./.github/actions/extract-azure-credentials
      with:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ env.AZURE_BLOB_STORAGE }}" \
          -backend-config="container_name=${{ env.AZURE_BLOB_STORAGE_TF_STATE_CONTAINER }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="resource_group_name=${{ vars.AZURE_RESOURCE_GROUP }}" \
          -backend-config="client_id=${{ steps.azure-creds.outputs.client_id }}" \
          -backend-config="client_secret=${{ steps.azure-creds.outputs.client_secret }}" \
          -backend-config="tenant_id=${{ steps.azure-creds.outputs.tenant_id }}" \
          -backend-config="subscription_id=${{ steps.azure-creds.outputs.subscription_id }}"

    - name: Set ARM_SUBSCRIPTION_ID
      id: subscription
      shell: bash
      run: |
        ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        if [ -z "$ARM_SUBSCRIPTION_ID" ]; then
          echo "Error: Could not retrieve subscription ID from Azure CLI"
          exit 1
        fi
        echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" >> $GITHUB_ENV
        echo "Subscription ID set successfully"

    - name: Terraform Destroy
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        TF_VAR_azure_resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
        TF_VAR_azure_owner_tag: ${{ vars.AZURE_OWNER_TAG }}
        TF_VAR_ssh_public_key_content: ${{ vars.PUBLIC_SSH_KEY_CONTENT }}
      run: terraform destroy -auto-approve -input=false
