name: 'Terraform Destroy'
description: 'Destroy Terraform-managed infrastructure in Azure'

inputs:
  working_directory:
    description: 'Working directory for Terraform'
    required: false
    default: './terraform'
  azure_resource_group:
    description: 'Azure resource group name'
    required: true
  azure_owner_tag:
    description: 'Azure owner tag'
    required: true
  ssh_public_key_content:
    description: 'SSH public key content'
    required: true
  client_id:
    description: 'Azure client ID'
    required: true
  client_secret:
    description: 'Azure client secret'
    required: true
  tenant_id:
    description: 'Azure tenant ID'
    required: true
  subscription_id:
    description: 'Azure subscription ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Parse tool versions
      uses: endorama/asdf-parse-tool-versions@v1.5.0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ env.AZURE_BLOB_STORAGE }}" \
          -backend-config="container_name=${{ env.AZURE_BLOB_STORAGE_TF_STATE_CONTAINER }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="resource_group_name=${{ inputs.azure_resource_group }}" \
          -backend-config="client_id=${{ inputs.client_id }}" \
          -backend-config="client_secret=${{ inputs.client_secret }}" \
          -backend-config="tenant_id=${{ inputs.tenant_id }}" \
          -backend-config="subscription_id=${{ inputs.subscription_id }}"

    - name: Set ARM_SUBSCRIPTION_ID
      id: subscription
      shell: bash
      run: |
        ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        if [ -z "$ARM_SUBSCRIPTION_ID" ]; then
          echo "Error: Could not retrieve subscription ID from Azure CLI"
          exit 1
        fi
        echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" >> $GITHUB_ENV
        echo "Subscription ID set successfully"

    - name: Terraform Destroy
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        TF_VAR_azure_resource_group: ${{ inputs.azure_resource_group }}
        TF_VAR_azure_owner_tag: ${{ inputs.azure_owner_tag }}
        TF_VAR_ssh_public_key_content: ${{ inputs.ssh_public_key_content }}
      run: terraform destroy -auto-approve -input=false
