name: 'Azure Authentication'
description: 'Authenticate to Azure using Service Principal credentials'

inputs:
  credentials:
    description: 'Azure credentials JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.credentials }}
