variable "azure_resource_group" {
  description = "Azure resource group"
  type        = string
}

variable "ssh_public_key_content" {
  type        = string
  description = "Ephemeral public key for automation (generated by runner/local scripts)"
  default     = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHZ/JWVNyc2lzgJZsjab8abaBjqobCYq21k1HQuqnoLD dummy@destroy"
}

variable "debug_ssh_public_key" {
  type        = string
  description = "Persistent debugging public key for manual SSH access"
  default     = ""
}

variable "ssh_user" {
  type        = string
  description = "SSH user"
  default     = "azureadm"
}

variable "azure_owner_tag" {
  type        = string
  description = "azure resources owner tag"
}
