name: 'Wait for SSH'
description: 'Wait for SSH to be available on all specified machines'

inputs:
  hosts_fqdn_list:
    description: 'Space-separated list of machine FQDNs to wait for'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  port_check_max_attempts:
    description: 'Maximum attempts to check if SSH port is open'
    required: false
    default: '20'
  port_check_wait_seconds:
    description: 'Seconds to wait between port check attempts'
    required: false
    default: '10'
  login_check_max_attempts:
    description: 'Maximum attempts to check if SSH login is permitted'
    required: false
    default: '15'
  login_check_wait_seconds:
    description: 'Seconds to wait between login check attempts'
    required: false
    default: '15'

runs:
  using: 'composite'
  steps:
    - name: Wait for SSH availability
      id: wait
      shell: bash
      run: |
        HOSTS_FQDN_LIST="${{ inputs.hosts_fqdn_list }}"
        SSH_USERNAME="${{ inputs.ssh_username }}"
        PORT_CHECK_MAX_ATTEMPTS="${{ inputs.port_check_max_attempts }}"
        PORT_CHECK_WAIT_SECONDS="${{ inputs.port_check_wait_seconds }}"
        LOGIN_CHECK_MAX_ATTEMPTS="${{ inputs.login_check_max_attempts }}"
        LOGIN_CHECK_WAIT_SECONDS="${{ inputs.login_check_wait_seconds }}"

        # Set log directory
        LOGS_DIR="logs"
        mkdir -p "$LOGS_DIR"

        # Track parallel jobs
        declare -a PIDS=()
        declare -A PID_TO_HOST=()

        total_hosts=$(echo $HOSTS_FQDN_LIST | wc -w)

        echo "================================================"
        echo "Waiting for SSH on $total_hosts machines in parallel"
        echo "================================================"
        echo ""

        # Function to wait for SSH on a single host
        wait_for_ssh() {
          local host=$1
          local log_file="$LOGS_DIR/ssh-wait-$host.log"

          {
            echo "⏳ Waiting for SSH port (22) to be available on $host..."
            local attempt=1
            while ! nc -z -w 5 "$host" 22; do
              if [ "$attempt" -ge "$PORT_CHECK_MAX_ATTEMPTS" ]; then
                echo "❌ SSH port not reachable after $attempt attempts on $host"
                return 1
              fi
              echo "   Attempt $attempt: Port 22 still closed, waiting ${PORT_CHECK_WAIT_SECONDS}s..."
              attempt=$((attempt+1))
              sleep "$PORT_CHECK_WAIT_SECONDS"
            done
            echo "✅ SSH port is available on $host"

            echo "⏳ Waiting for remote login to be permitted..."
            local login_attempt=1

            while ! ssh -o StrictHostKeyChecking=accept-new \
                        -o ConnectTimeout=5 \
                        -i ~/.ssh/id_rsa \
                        "$SSH_USERNAME@$host" \
                        true 2>/dev/null; do
              if [ "$login_attempt" -ge "$LOGIN_CHECK_MAX_ATTEMPTS" ]; then
                echo "❌ Remote login not permitted after $login_attempt attempts on $host"
                return 1
              fi
              echo "   Login attempt $login_attempt: Still booting, waiting ${LOGIN_CHECK_WAIT_SECONDS}s..."
              login_attempt=$((login_attempt+1))
              sleep "$LOGIN_CHECK_WAIT_SECONDS"
            done
            echo "✅ SSH login is now permitted on $host"

            return 0
          } > "$log_file" 2>&1
        }

        # Launch SSH wait for each host in parallel
        for host in $HOSTS_FQDN_LIST; do
          echo "Launching SSH wait for $host..."

          wait_for_ssh "$host" &

          # Track process
          current_pid=$!
          PIDS+=("$current_pid")
          PID_TO_HOST["$current_pid"]="$host"
        done

        echo ""
        echo "All SSH wait jobs launched. Waiting for completion..."
        echo ""

        # Wait for all jobs to complete and collect results
        ready_count=0
        failed_hosts=""

        for pid in "${PIDS[@]}"; do
          host="${PID_TO_HOST[$pid]}"

          if wait "$pid"; then
            echo "✓ SSH ready on $host"
            ready_count=$((ready_count + 1))
          else
            echo "✗ SSH not ready on $host"
            log_file="$LOGS_DIR/ssh-wait-$host.log"
            if [ -f "$log_file" ]; then
              echo "  Error details (last 30 lines):"
              tail -n 30 "$log_file" | sed 's/^/  /'
            fi
            failed_hosts="$failed_hosts $host"
          fi
        done

        # Print summary
        echo ""
        echo "================================================"
        echo "SSH Readiness Summary"
        echo "================================================"
        echo "Total machines: $total_hosts"
        echo "SSH ready: $ready_count"
        echo "Failed: $((total_hosts - ready_count))"

        if [ -n "$failed_hosts" ]; then
          echo ""
          echo "Failed hosts:$failed_hosts"
        fi
        echo "================================================"
        echo ""
        echo "Detailed logs saved to: $LOGS_DIR/"

        # Check if any SSH waits failed
        if [ -n "$failed_hosts" ]; then
          echo ""
          echo "Error: SSH not ready on $((total_hosts - ready_count)) machine(s)"
          exit 1
        fi

        echo ""
        echo "✓ SSH ready on all machines!"
