name: 'Activate SUSE Modules'
description: 'Activate SUSE modules (basesystem, PackageHub, legacy) on machines via SSH'

inputs:
  hosts_fqdn_list:
    description: 'Space-separated list of machine FQDNs to activate modules on'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key content'
    required: true
  connection_timeout:
    description: 'SSH connection timeout in seconds'
    required: false
    default: '60'

runs:
  using: 'composite'
  steps:
    - name: Convert hosts list to comma-separated format
      id: prepare-hosts
      shell: bash
      run: |
        HOSTS_FQDN_LIST="${{ inputs.hosts_fqdn_list }}"
        # Convert space-separated list to comma-separated
        HOSTS_CSV=$(echo $HOSTS_FQDN_LIST | tr ' ' ',')
        echo "hosts_csv=$HOSTS_CSV" >> $GITHUB_OUTPUT
        echo "Hosts to activate: $HOSTS_CSV"

    - name: Activate SUSE modules on machines
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ steps.prepare-hosts.outputs.hosts_csv }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_private_key }}
        timeout: 5m
        command_timeout: 5m
        script: |
          # Skip SLES 16 machines silently
          if echo "$(hostname)" | grep -q "sles16"; then
            exit 0
          fi

          # Extract service pack version from hostname
          SP=$(hostname | grep -o "sp[4-7]" | cut -c3-)

          if [ -z "$SP" ]; then
            echo "Error: Could not determine service pack version from hostname: $(hostname)"
            exit 1
          fi

          echo "Activating modules for SLES 15.${SP} on $(hostname)..."

          # Activate base module
          sudo SUSEConnect -p sle-module-basesystem/15.$SP/x86_64

          # Activate PackageHub
          sudo SUSEConnect -p PackageHub/15.$SP/x86_64

          # Activate legacy module only for SP6
          if [ "$SP" -eq 6 ]; then
            sudo SUSEConnect -p sle-module-legacy/15.$SP/x86_64
          fi

          echo "Module activation completed for $(hostname)"

    - name: Verify activated modules
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ steps.prepare-hosts.outputs.hosts_csv }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_private_key }}
        timeout: 60s
        command_timeout: 60s
        script: |
          # Skip SLES 16 machines
          if echo "$(hostname)" | grep -q "sles16"; then
            exit 0
          fi

          echo "=== $(hostname) ==="
          sudo SUSEConnect --status-text

