name: 'Setup RPM Repository'
description: 'Setup local RPM repository on control and target machines from Azure blob storage'

inputs:
  hosts_fqdn_csv:
    description: 'Comma-separated list of machine FQDNs'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key content'
    required: true
  azure_blob_storage:
    description: 'Azure blob storage account name'
    required: true
  azure_blob_storage_container:
    description: 'Azure blob storage container name'
    required: true
  azure_blob_storage_sas_token:
    description: 'Azure blob storage SAS token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup RPM repository on machines
      uses: appleboy/ssh-action@v1.2.4
      with:
        host: ${{ inputs.hosts_fqdn_csv }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_private_key }}
        script: |
          set -e

          HOSTNAME=$(hostname)

          # Extract SLES version from /etc/os-release (e.g., VERSION_ID="15.4")
          source /etc/os-release
          SLES_MAJOR_VERSION="${VERSION_ID%%.*}"
          SP_VERSION="${VERSION_ID##*.}"

          # Build version-specific blob storage URL
          URL_BASE="https://${{ inputs.azure_blob_storage }}.blob.core.windows.net/${{ inputs.azure_blob_storage_container }}"
          URL_ORIGIN="$URL_BASE/$SLES_MAJOR_VERSION/$SP_VERSION/?${{ inputs.azure_blob_storage_sas_token }}"

          # Install azcopy
          sudo zypper --non-interactive --gpg-auto-import-keys addrepo https://packages.microsoft.com/sles/15/prod/ microsoft-prod 2>/dev/null || true
          sudo zypper --non-interactive --gpg-auto-import-keys refresh
          sudo zypper --non-interactive --gpg-auto-import-keys install -y azcopy

          if [[ "$HOSTNAME" == target* ]]; then
            # Target nodes: setup full local RPM repository
            sudo mkdir -p /var/cache/zypper/custom_repo
            sudo azcopy cp "$URL_BASE/$SLES_MAJOR_VERSION/$SP_VERSION/*?${{ inputs.azure_blob_storage_sas_token }}" /var/cache/zypper/custom_repo --recursive=true --exclude-pattern "ansible-trento-*.rpm"

            # Create local repository
            sudo zypper --non-interactive --gpg-auto-import-keys install --auto-agree-with-licenses createrepo_c
            sudo createrepo_c /var/cache/zypper/custom_repo

            # Configure zypper to use the local repository
            echo -e '[custom_rpms]\nname=Local Custom RPMs\nbaseurl=file:///var/cache/zypper/custom_repo/\nenabled=1\ngpgcheck=0\npriority=1' | sudo tee /etc/zypp/repos.d/custom_rpms.repo > /dev/null
            sudo zypper clean --all
            sudo zypper --non-interactive --gpg-auto-import-keys refresh
            exit 0
          fi

          # Control nodes: just download and install ansible-trento directly
          TEMP_DIR=$(mktemp -d)
          azcopy cp "$URL_BASE/$SLES_MAJOR_VERSION/$SP_VERSION/*?${{ inputs.azure_blob_storage_sas_token }}" "$TEMP_DIR" --recursive=true --include-pattern "ansible-trento-*.rpm"
          sudo zypper --non-interactive --gpg-auto-import-keys install --allow-unsigned-rpm --auto-agree-with-licenses "$TEMP_DIR"/ansible-trento-*.rpm
          rm -rf "$TEMP_DIR"
