name: 'Setup RPM Repository'
description: 'Setup local RPM repository on control and target machines from Azure blob storage'

inputs:
  hosts_fqdn_list:
    description: 'Space-separated list of machine FQDNs'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key content'
    required: true
  azure_blob_storage:
    description: 'Azure blob storage account name'
    required: true
  azure_blob_storage_container:
    description: 'Azure blob storage container name'
    required: true
  azure_blob_storage_sas_token:
    description: 'Azure blob storage SAS token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Filter and prepare hosts list
      id: prepare-hosts
      shell: bash
      run: |
        HOSTS_FQDN_LIST="${{ inputs.hosts_fqdn_list }}"

        # Filter hosts to only include control and target machines
        target_hosts=""
        for host in $HOSTS_FQDN_LIST; do
          hostname_base="${host%%.*}"
          if [[ "$hostname_base" == control* ]] || [[ "$hostname_base" == target* ]]; then
            target_hosts="$target_hosts $host"
          fi
        done

        # Trim and convert to comma-separated
        HOSTS_CSV=$(echo $target_hosts | xargs | tr ' ' ',')
        echo "hosts_csv=$HOSTS_CSV" >> $GITHUB_OUTPUT

    - name: Setup RPM repository on machines
      if: steps.prepare-hosts.outputs.hosts_csv != ''
      uses: appleboy/ssh-action@v1.2.4
      with:
        host: ${{ steps.prepare-hosts.outputs.hosts_csv }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_private_key }}
        script: |
          set -e

          HOSTNAME=$(hostname)

          # Extract SLES version from hostname (e.g., control15sp4rpm -> 15, 4)
          if [[ "$HOSTNAME" =~ ([0-9]+)sp([0-9]+) ]]; then
            SLES_MAJOR_VERSION="${BASH_REMATCH[1]}"
            SP_VERSION="${BASH_REMATCH[2]}"
          else
            exit 1
          fi

          # Build version-specific blob storage URL
          URL_BASE="https://${{ inputs.azure_blob_storage }}.blob.core.windows.net/${{ inputs.azure_blob_storage_container }}"
          URL_ORIGIN="$URL_BASE/$SLES_MAJOR_VERSION/$SP_VERSION/?${{ inputs.azure_blob_storage_sas_token }}"

          # Install azcopy
          sudo zypper --non-interactive --gpg-auto-import-keys addrepo https://packages.microsoft.com/sles/15/prod/ microsoft-prod 2>/dev/null || true
          sudo zypper --non-interactive --gpg-auto-import-keys refresh
          sudo zypper --non-interactive --gpg-auto-import-keys install -y azcopy

          if [[ "$HOSTNAME" == control* ]]; then
            # Control nodes: just download and install ansible-trento directly
            TEMP_DIR=$(mktemp -d)
            azcopy cp "$URL_BASE/$SLES_MAJOR_VERSION/$SP_VERSION/*?${{ inputs.azure_blob_storage_sas_token }}" "$TEMP_DIR" --recursive=true --include-pattern "ansible-trento-*.rpm"
            sudo zypper --non-interactive --gpg-auto-import-keys install --auto-agree-with-licenses "$TEMP_DIR"/ansible-trento-*.rpm
            rm -rf "$TEMP_DIR"
          else
            # Target nodes: setup full local RPM repository
            sudo mkdir -p /var/cache/zypper/custom_repo
            sudo azcopy cp "$URL_BASE/$SLES_MAJOR_VERSION/$SP_VERSION/*?${{ inputs.azure_blob_storage_sas_token }}" /var/cache/zypper/custom_repo --recursive=true --exclude-pattern "ansible-trento-*.rpm"

            # Create local repository
            sudo zypper --non-interactive --gpg-auto-import-keys install --auto-agree-with-licenses createrepo_c
            sudo createrepo_c /var/cache/zypper/custom_repo

            # Configure zypper to use the local repository
            echo -e '[custom_rpms]\nname=Local Custom RPMs\nbaseurl=file:///var/cache/zypper/custom_repo/\nenabled=1\ngpgcheck=0\npriority=1' | sudo tee /etc/zypp/repos.d/custom_rpms.repo > /dev/null
            sudo zypper clean --all
            sudo zypper --non-interactive --gpg-auto-import-keys refresh
          fi
