name: 'Generate Ansible Inventory'
description: 'Generate Ansible inventory file on control nodes with their matching target node'

inputs:
  control_hosts_fqdn_list:
    description: 'Space-separated list of control node FQDNs'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key content'
    required: true
  web_admin_password:
    description: 'Trento web admin password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Convert hosts list to comma-separated format
      id: prepare-hosts
      shell: bash
      run: |
        HOSTS_FQDN_LIST="${{ inputs.control_hosts_fqdn_list }}"
        # Convert space-separated list to comma-separated
        HOSTS_CSV=$(echo $HOSTS_FQDN_LIST | tr ' ' ',')
        echo "hosts_csv=$HOSTS_CSV" >> $GITHUB_OUTPUT

    - name: Generate Ansible inventory on control nodes
      uses: appleboy/ssh-action@v1.2.4
      env:
        SSH_USERNAME: ${{ inputs.ssh_username }}
        WEB_ADMIN_PASSWORD: ${{ inputs.web_admin_password }}
      with:
        host: ${{ steps.prepare-hosts.outputs.hosts_csv }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_private_key }}
        envs: SSH_USERNAME,WEB_ADMIN_PASSWORD
        script: |
          set -e

          # Get current hostname (short name, e.g., control15sp6rpm)
          CURRENT_HOSTNAME=$(hostname -s)

          # Only run on control nodes
          if [[ "$CURRENT_HOSTNAME" != *control* ]]; then
            exit 0
          fi

          # Construct Azure public FQDN from short hostname
          AZURE_REGION="westeurope"
          CURRENT_FQDN="${CURRENT_HOSTNAME}.${AZURE_REGION}.cloudapp.azure.com"

          # Derive target FQDN by replacing 'control' with 'target'
          TARGET_FQDN="${CURRENT_FQDN/control/target}"

          # Determine Python interpreter based on OS version
          source /etc/os-release
          if [[ "$VERSION_ID" == 15.[67] ]]; then
            PYTHON_INTERPRETER="/usr/bin/python3.11"
          else
            PYTHON_INTERPRETER="/usr/bin/python3"
          fi

          # Create Ansible inventory directory if it doesn't exist
          sudo mkdir -p /etc/ansible

          # Generate the inventory file
          sudo tee /etc/ansible/trento-inventory.yml > /dev/null << EOF
          all:
            children:
              trento_hosts:
                vars:
                  ansible_python_interpreter: $PYTHON_INTERPRETER
                  provision_prometheus: false
                  provision_proxy: true
                  web_postgres_password: "postgres"
                  wanda_postgres_password: "postgres"
                  rabbitmq_password: "admin"
                  web_admin_password: "$WEB_ADMIN_PASSWORD"
                  web_port: 4000
                  wanda_port: 4001
                  trento_server_name: "{{ inventory_hostname }}"
                  nginx_vhost_filename: "{{ inventory_hostname }}"
                hosts:
                  ${TARGET_FQDN}:
                    ansible_user: $SSH_USERNAME
              trento_server:
                children:
                  trento_hosts: {}
              postgres_hosts:
                children:
                  trento_hosts: {}
              rabbitmq_hosts:
                children:
                  trento_hosts: {}
          EOF
