name: 'Generate Machine Matrix'
description: 'Generate a matrix of machine names from a CSV configuration file'

inputs:
  csv_file:
    description: 'Path to the CSV file containing machine configuration'
    required: true
    default: '.machines.conf.csv'
  output_file:
    description: 'Path where the matrix JSON file will be saved'
    required: true
    default: 'matrix.json'

outputs:
  matrix_file:
    description: 'Path to the generated matrix JSON file'
    value: ${{ steps.generate.outputs.matrix_file }}
  machine_count:
    description: 'Number of machines in the matrix'
    value: ${{ steps.generate.outputs.machine_count }}

runs:
  using: 'composite'
  steps:
    - name: Generate matrix from CSV
      id: generate
      shell: bash
      run: |
        CSV_FILE="${{ inputs.csv_file }}"
        OUTPUT_FILE="${{ inputs.output_file }}"

        # Check if CSV file exists
        if [ ! -f "$CSV_FILE" ]; then
          echo "Error: $CSV_FILE does not exist"
          exit 1
        fi

        # Generate matrix from CSV
        matrix=$(tail -n +2 "$CSV_FILE" | grep -v '^[[:space:]]*$' | while IFS=, read -r prefix slesVersion spVersion suffix; do
          prefix=$(echo "$prefix" | tr -d '\r' | xargs)
          slesVersion=$(echo "$slesVersion" | tr -d '\r' | xargs)
          spVersion=$(echo "$spVersion" | tr -d '\r' | xargs)
          suffix=$(echo "$suffix" | tr -d '\r' | xargs)

          if [ -n "$prefix" ]; then
            vm_name="${prefix}${slesVersion}sp${spVersion}${suffix}"
            echo "{\"name\":\"$vm_name\"}"
          fi
        done | jq -s -c '.')

        # Check if matrix is empty
        if [ "$matrix" = "[]" ] || [ -z "$matrix" ]; then
          echo "Error: No machines found in $CSV_FILE"
          exit 1
        fi

        # Save to file
        echo "$matrix" > "$OUTPUT_FILE"

        # Set outputs
        machine_count=$(echo "$matrix" | jq 'length')
        echo "matrix_file=$OUTPUT_FILE" >> $GITHUB_OUTPUT
        echo "machine_count=$machine_count" >> $GITHUB_OUTPUT
        echo "Generated matrix for $machine_count machines"
