name: 'Register SUSE Machines'
description: 'Register SUSE machines with SUSEConnect via SSH'

inputs:
  hosts_fqdn_list:
    description: 'Space-separated list of machine FQDNs to register'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
    default: 'cloudadmin'
  registration_code:
    description: 'SUSE registration code'
    required: true
  registration_email:
    description: 'SUSE registration email'
    required: true
  connection_timeout:
    description: 'SSH connection timeout in seconds'
    required: false
    default: '60'

outputs:
  registered_count:
    description: 'Number of machines successfully registered'
    value: ${{ steps.register.outputs.registered_count }}
  failed_hosts:
    description: 'List of hosts that failed to register'
    value: ${{ steps.register.outputs.failed_hosts }}
  logs_dir:
    description: 'Directory containing registration logs'
    value: ${{ steps.register.outputs.logs_dir }}

runs:
  using: 'composite'
  steps:
    - name: Register machines with SUSEConnect
      id: register
      shell: bash
      run: |
        set -x  # Enable debug mode to see commands being executed

        HOSTS_FQDN_LIST="${{ inputs.hosts_fqdn_list }}"
        SSH_USERNAME="${{ inputs.ssh_username }}"
        CONNECTION_TIMEOUT="${{ inputs.connection_timeout }}"
        REGISTRATION_CODE="${{ inputs.registration_code }}"
        REGISTRATION_EMAIL="${{ inputs.registration_email }}"

        echo "DEBUG: SSH_USERNAME=$SSH_USERNAME"
        echo "DEBUG: CONNECTION_TIMEOUT=$CONNECTION_TIMEOUT"
        echo "DEBUG: REGISTRATION_CODE is set: $([ -n "$REGISTRATION_CODE" ] && echo 'yes' || echo 'no')"
        echo "DEBUG: REGISTRATION_EMAIL is set: $([ -n "$REGISTRATION_EMAIL" ] && echo 'yes' || echo 'no')"
        echo "DEBUG: Number of hosts: $(echo $HOSTS_FQDN_LIST | wc -w)"

        # Set log directory
        LOGS_DIR="logs"

        echo "DEBUG: Checking if logs directory exists..."
        ls -la logs/ || echo "logs/ directory not found"

        # Track registration results
        registered_count=0
        failed_hosts=""
        total_hosts=$(echo $HOSTS_FQDN_LIST | wc -w)
        current=0

        echo "================================================"
        echo "Starting registration of $total_hosts machines"
        echo "================================================"
        echo ""

        # Loop through each host and register
        for host in $HOSTS_FQDN_LIST; do
          ((current++))
          echo ""
          echo "[$current/$total_hosts] Registering $host..."
          echo "DEBUG: Creating log file for $host"

          # Create log file for this host
          log_file="$LOGS_DIR/registration-$host.log"
          echo "DEBUG: Log file path: $log_file"

          echo "DEBUG: Checking SSH key exists..."
          ls -la ~/.ssh/id_rsa || echo "SSH key not found!"

          echo "DEBUG: Attempting SSH connection to $SSH_USERNAME@$host..."

          # Run SUSEConnect via SSH
          if ssh -o StrictHostKeyChecking=accept-new \
                 -o ConnectTimeout="$CONNECTION_TIMEOUT" \
                 -i ~/.ssh/id_rsa \
                 "$SSH_USERNAME@$host" \
                 "sudo SUSEConnect -r '$REGISTRATION_CODE' -e '$REGISTRATION_EMAIL'" \
                 > "$log_file" 2>&1; then
            echo "  ✓ Successfully registered $host"
            ((registered_count++))
          else
            exit_code=$?
            echo "  ✗ Failed to register $host (exit code: $exit_code)"
            echo ""
            echo "  Error details (last 30 lines):"
            if [ -f "$log_file" ]; then
              tail -n 30 "$log_file" | sed 's/^/    /'
            else
              echo "    Log file not found: $log_file"
            fi
            echo ""
            failed_hosts="$failed_hosts $host"
          fi
        done

        # Print summary
        echo ""
        echo "================================================"
        echo "Registration Summary"
        echo "================================================"
        echo "Total machines: $total_hosts"
        echo "Successfully registered: $registered_count"
        echo "Failed: $((total_hosts - registered_count))"

        if [ -n "$failed_hosts" ]; then
          echo ""
          echo "Failed hosts:$failed_hosts"
        fi
        echo "================================================"
        echo ""
        echo "Detailed logs saved to: $LOGS_DIR/"

        # Set outputs
        echo "registered_count=$registered_count" >> $GITHUB_OUTPUT
        echo "failed_hosts=$failed_hosts" >> $GITHUB_OUTPUT
        echo "logs_dir=$LOGS_DIR" >> $GITHUB_OUTPUT

        # Check if any registrations failed
        if [ -n "$failed_hosts" ]; then
          echo ""
          echo "Error: Failed to register $((total_hosts - registered_count)) machine(s)"
          exit 1
        fi

        echo ""
        echo "✓ All machines registered successfully!"
