name: 'Register SUSE Machines'
description: 'Register SUSE machines with SUSEConnect via SSH'

inputs:
  hosts_fqdn_list:
    description: 'Space-separated list of machine FQDNs to register'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
    default: 'cloudadmin'
  registration_code:
    description: 'SUSE registration code'
    required: true
  registration_email:
    description: 'SUSE registration email'
    required: true
  connection_timeout:
    description: 'SSH connection timeout in seconds'
    required: false
    default: '120'

runs:
  using: 'composite'
  steps:
    - name: Register machines with SUSEConnect
      id: register
      shell: bash
      run: |
        HOSTS_FQDN_LIST="${{ inputs.hosts_fqdn_list }}"
        SSH_USERNAME="${{ inputs.ssh_username }}"
        CONNECTION_TIMEOUT="${{ inputs.connection_timeout }}"
        REGISTRATION_CODE="${{ inputs.registration_code }}"
        REGISTRATION_EMAIL="${{ inputs.registration_email }}"

        # Set log directory
        LOGS_DIR="logs"

        # Track parallel jobs
        declare -a PIDS=()
        declare -A PID_TO_HOST=()

        total_hosts=$(echo $HOSTS_FQDN_LIST | wc -w)

        echo "================================================"
        echo "Registering $total_hosts machines in parallel"
        echo "================================================"
        echo ""

        # Launch registration for each host in parallel
        for host in $HOSTS_FQDN_LIST; do
          log_file="$LOGS_DIR/registration-$host.log"

          echo "Launching registration for $host..."

          # Run SUSEConnect via SSH in background
          ssh -o StrictHostKeyChecking=accept-new \
              -o ConnectTimeout="$CONNECTION_TIMEOUT" \
              -i ~/.ssh/id_rsa \
              "$SSH_USERNAME@$host" \
              "sudo SUSEConnect -r '$REGISTRATION_CODE' -e '$REGISTRATION_EMAIL'" \
              > "$log_file" 2>&1 &

          # Track process
          current_pid=$!
          PIDS+=("$current_pid")
          PID_TO_HOST["$current_pid"]="$host"
        done

        echo ""
        echo "All registration jobs launched. Waiting for completion..."
        echo ""

        # Wait for all jobs to complete and collect results
        registered_count=0
        failed_hosts=""

        for pid in "${PIDS[@]}"; do
          host="${PID_TO_HOST[$pid]}"

          if wait "$pid"; then
            echo "✓ Successfully registered $host"
            registered_count=$((registered_count + 1))
          else
            echo "✗ Failed to register $host"
            log_file="$LOGS_DIR/registration-$host.log"
            if [ -f "$log_file" ]; then
              echo "  Error details (last 30 lines):"
              tail -n 30 "$log_file" | sed 's/^/  /'
            fi
            failed_hosts="$failed_hosts $host"
          fi
        done

        # Print summary
        echo ""
        echo "================================================"
        echo "Registration Summary"
        echo "================================================"
        echo "Total machines: $total_hosts"
        echo "Successfully registered: $registered_count"
        echo "Failed: $((total_hosts - registered_count))"

        if [ -n "$failed_hosts" ]; then
          echo ""
          echo "Failed hosts:$failed_hosts"
        fi
        echo "================================================"
        echo ""
        echo "Detailed logs saved to: $LOGS_DIR/"

        # Check if any registrations failed
        if [ -n "$failed_hosts" ]; then
          echo ""
          echo "Error: Failed to register $((total_hosts - registered_count)) machine(s)"
          exit 1
        fi

        echo ""
        echo "✓ All machines registered successfully!"
