name: 'Register SUSE Machines, Activate Modules & Install Python'
description: 'Register machines with SUSEConnect, activate SUSE modules (basesystem, PackageHub, legacy), and install Python via SSH'

inputs:
  hosts_fqdn_csv:
    description: 'Comma-separated list of machine FQDNs'
    required: true
  ssh_username:
    description: 'SSH username'
    required: true
  ssh_private_key:
    description: 'SSH private key content'
    required: true
  registration_code:
    description: 'SUSE registration code'
    required: true
  registration_email:
    description: 'SUSE registration email'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Activate SUSE modules & Install Python
      uses: appleboy/ssh-action@v1.2.4
      with:
        host: ${{ inputs.hosts_fqdn_csv }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_private_key }}
        script: |
          set -e

          source /etc/os-release

          sudo SUSEConnect -r '${{ inputs.registration_code }}' -e '${{ inputs.registration_email }}'

          if [[ "$VERSION_ID" != 16* ]]; then
            sudo SUSEConnect -p sle-module-basesystem/$VERSION_ID/x86_64
          fi
          sudo SUSEConnect -p PackageHub/$VERSION_ID/x86_64

          if [[ "$VERSION_ID" == "15.6" ]]; then
            sudo SUSEConnect -p sle-module-legacy/$VERSION_ID/x86_64
          fi

          if [[ "$VERSION_ID" == "15.4" ]] && [[ "$(hostname)" == target* ]]; then
            sudo SUSEConnect -p sle-module-python3/$VERSION_ID/x86_64
          fi

          # Install Python 3.11 for Ansible 11 compatibility (both control and target nodes)            
          # sudo zypper --non-interactive --gpg-auto-import-keys install --no-recommends --auto-agree-with-licenses python311-base

