# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Provision Infrastructure

on:
  workflow_dispatch:
    inputs:
      sles_15_sp4:
        description: 'Deploy to SLES 15 SP4'
        type: boolean
        default: true
      sles_15_sp5:
        description: 'Deploy to SLES 15 SP5'
        type: boolean
        default: true
      sles_15_sp6:
        description: 'Deploy to SLES 15 SP6'
        type: boolean
        default: true
      sles_15_sp7:
        description: 'Deploy to SLES 15 SP7'
        type: boolean
        default: true
      sles_16_0:
        description: 'Deploy to SLES 16'
        type: boolean
        default: true
      package_source:
        description: 'Package repository source to configure on machines'
        type: choice
        default: 'blob_storage'
        options:
          - 'blob_storage'
          - 'rolling'

jobs:
  provision:
    name: Provision infrastructure
    uses: ./.github/workflows/trento-installation-base.yml
    with:
      sles_15_sp4: ${{ inputs.sles_15_sp4 }}
      sles_15_sp5: ${{ inputs.sles_15_sp5 }}
      sles_15_sp6: ${{ inputs.sles_15_sp6 }}
      sles_15_sp7: ${{ inputs.sles_15_sp7 }}
      sles_16_0: ${{ inputs.sles_16_0 }}
      package_source: ${{ inputs.package_source }}
      provision_only: true
    secrets: inherit
