# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Trento Installation Tests

on:
  workflow_dispatch:
    inputs:
      sles_15_sp4:
        description: 'Deploy to SLES 15 SP4'
        type: boolean
        default: true
      sles_15_sp5:
        description: 'Deploy to SLES 15 SP5'
        type: boolean
        default: true
      sles_15_sp6:
        description: 'Deploy to SLES 15 SP6'
        type: boolean
        default: true
      sles_15_sp7:
        description: 'Deploy to SLES 15 SP7'
        type: boolean
        default: true
      sles_16_0:
        description: 'Deploy to SLES 16'
        type: boolean
        default: true
      install_rolling:
        description: 'Install rolling version of packages'
        type: boolean
        default: false
      skip_cypress:
        description: 'Skip the Cypress end-to-end tests'
        type: boolean
        default: false

jobs:
  installation-tests:
    name: Run installation tests
    uses: ./.github/workflows/trento-installation-base.yml
    with:
      sles_15_sp4: ${{ inputs.sles_15_sp4 }}
      sles_15_sp5: ${{ inputs.sles_15_sp5 }}
      sles_15_sp6: ${{ inputs.sles_15_sp6 }}
      sles_15_sp7: ${{ inputs.sles_15_sp7 }}
      sles_16_0: ${{ inputs.sles_16_0 }}
      install_rolling: ${{ inputs.install_rolling }}
      skip_cypress: ${{ inputs.skip_cypress }}
    secrets: inherit
